name: open_vibrance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  hotkey_manager: ^0.2.3
  record: ^6.0.0
  screen_retriever: ^0.2.0
  window_manager: ^0.4.3
  http: ^0.13.6
  http_parser: ^4.0.0
  flutter_secure_storage: ^8.0.0
  clipboard: ^0.1.3
  keypress_simulator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
